apiVersion: workloads.gke.io/v1
kind: WorkloadClass
metadata:
  name: critical-workload
  namespace: demo
spec:
  podSelector:
    matchLabels:
      workload-class: production-batch
  disruptionPolicy:
    allowedDisruptionWindows:
      - name: "weekend-maintenance"
        daysOfWeek:
          - Sunday
          - Saturday
        startTime: "00:00"
        endTime: "23:59"
        timeZone: "America/Toronto"
    maxNonDisruptionDurationDays: 1
    allowedDisruptionsOutsideOfWindow:
      - VPA
      - ClusterAutoscaler
