//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisruptionWindow) DeepCopyInto(out *DisruptionWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisruptionWindow.
func (in *DisruptionWindow) DeepCopy() *DisruptionWindow {
	if in == nil {
		return nil
	}
	out := new(DisruptionWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClass) DeepCopyInto(out *WorkloadClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClass.
func (in *WorkloadClass) DeepCopy() *WorkloadClass {
	if in == nil {
		return nil
	}
	out := new(WorkloadClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClassGuardrail) DeepCopyInto(out *WorkloadClassGuardrail) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClassGuardrail.
func (in *WorkloadClassGuardrail) DeepCopy() *WorkloadClassGuardrail {
	if in == nil {
		return nil
	}
	out := new(WorkloadClassGuardrail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadClassGuardrail) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClassGuardrailList) DeepCopyInto(out *WorkloadClassGuardrailList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadClassGuardrail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClassGuardrailList.
func (in *WorkloadClassGuardrailList) DeepCopy() *WorkloadClassGuardrailList {
	if in == nil {
		return nil
	}
	out := new(WorkloadClassGuardrailList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadClassGuardrailList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClassGuardrailSpec) DeepCopyInto(out *WorkloadClassGuardrailSpec) {
	*out = *in
	if in.MaxWindowDurationMinutes != nil {
		in, out := &in.MaxWindowDurationMinutes, &out.MaxWindowDurationMinutes
		*out = new(int32)
		**out = **in
	}
	if in.MaxWindowsPerWeek != nil {
		in, out := &in.MaxWindowsPerWeek, &out.MaxWindowsPerWeek
		*out = new(int32)
		**out = **in
	}
	if in.MinInitialRunDurationDaysLimit != nil {
		in, out := &in.MinInitialRunDurationDaysLimit, &out.MinInitialRunDurationDaysLimit
		*out = new(int32)
		**out = **in
	}
	if in.MaxNonDisruptionDurationDaysLimit != nil {
		in, out := &in.MaxNonDisruptionDurationDaysLimit, &out.MaxNonDisruptionDurationDaysLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClassGuardrailSpec.
func (in *WorkloadClassGuardrailSpec) DeepCopy() *WorkloadClassGuardrailSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadClassGuardrailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClassGuardrailStatus) DeepCopyInto(out *WorkloadClassGuardrailStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClassGuardrailStatus.
func (in *WorkloadClassGuardrailStatus) DeepCopy() *WorkloadClassGuardrailStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadClassGuardrailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClassList) DeepCopyInto(out *WorkloadClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClassList.
func (in *WorkloadClassList) DeepCopy() *WorkloadClassList {
	if in == nil {
		return nil
	}
	out := new(WorkloadClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClassSpec) DeepCopyInto(out *WorkloadClassSpec) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedDisruptionWindows != nil {
		in, out := &in.AllowedDisruptionWindows, &out.AllowedDisruptionWindows
		*out = make([]DisruptionWindow, len(*in))
		copy(*out, *in)
	}
	if in.AllowedDisruptionsOutsideOfWindow != nil {
		in, out := &in.AllowedDisruptionsOutsideOfWindow, &out.AllowedDisruptionsOutsideOfWindow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnforcedDisruptionTimeoutSeconds != nil {
		in, out := &in.EnforcedDisruptionTimeoutSeconds, &out.EnforcedDisruptionTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClassSpec.
func (in *WorkloadClassSpec) DeepCopy() *WorkloadClassSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClassStatus) DeepCopyInto(out *WorkloadClassStatus) {
	*out = *in
	if in.LastDisruptionTime != nil {
		in, out := &in.LastDisruptionTime, &out.LastDisruptionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClassStatus.
func (in *WorkloadClassStatus) DeepCopy() *WorkloadClassStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadClassStatus)
	in.DeepCopyInto(out)
	return out
}
