## Append samples of your project ##
resources:
- sample_namespace.yaml
- workloads_v1_workloadclassguardrail.yaml
- workloads_v1_workloadclass.yaml
- dummy_pod.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
